### ISSUE TITLE
Test with kitchen: cannot load such file -- acme-client

### ISSUE THREAD

**Issue by Dragsbaek** [schubergphilis/chef-acme#118]
Im getting `Acme library dependency 'acme-client' not loaded: cannot load such file -- acme-client` when running kitchen. 

How do i set up kitchen to work with chef-acme?

**Comment by thoutenbos** [comment]
Did you include the recipe in your runlist? This will install the required gem

**Comment by Dragsbaek** [comment]
Yes, i have it in my runlist. Also tried including it before everything else, like this:

```
suites:
  - name: default
    run_list:
      - recipe[acme]
      - recipe[webserver::default]
```

I also tried copying acme_server and acme_client from fixtures/cookbooks and referencing from berksfile, like this:

```
# Test
group :integration do
    # Self-hosted acme server
    cookbook 'acme_client', path: 'test/fixtures/cookbooks/acme_client'
    cookbook 'acme_server', path: 'test/fixtures/cookbooks/acme_server'
end
```
